apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busy-pv
  name: busy-pv
spec:
  containers:
  - image: busybox
    name: busy-pv
    resources: {}
    volumeMounts:
      - name: foo
        mountPath: /etc/foo
    command:
    - sh
    - -c
    - sleep 3600
  - image: busybox
    name: busy-pv2
    resources: {}
    command:
    - sh
    - -c
    - sleep 3600
    volumeMounts:
      - name: foo
        mountPath: /etc/foo
  volumes:
  - emptyDir: {}
    name: foo
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
